# -*- mode: python ; coding: utf-8 -*-
"""
AI日志分析器 - 常驻分析服务 PyInstaller 配置文件

仅包含 serve 命令所需模块，排除 Web/Flask 等依赖以减小体积。
"""

import sys
import os

block_cipher = None

# 获取项目根目录（spec文件在scripts目录，需要往上一层）
project_root = os.path.dirname(os.path.dirname(os.path.abspath(SPEC)))

a = Analysis(
    [os.path.join(project_root, 'main_serve.py')],
    pathex=[project_root],
    binaries=[],
    datas=[
        # 配置文件（打包到exe内部作为默认值）
        (os.path.join(project_root, 'config/*.json'), 'config'),
        # 源代码模块
        (os.path.join(project_root, 'src'), 'src'),
        # 插件系统（只打包必要的文件）
        (os.path.join(project_root, 'plugins/__init__.py'), 'plugins'),
        (os.path.join(project_root, 'plugins/base.py'), 'plugins'),
        (os.path.join(project_root, 'plugins/manager.py'), 'plugins'),
        (os.path.join(project_root, 'plugins/builtin'), 'plugins/builtin'),
        (os.path.join(project_root, 'plugins/renderer'), 'plugins/renderer'),
        (os.path.join(project_root, 'plugins/README.md'), 'plugins'),
        # 自定义插件目录（空目录占位）
        (os.path.join(project_root, 'custom_plugins/__init__.py'), 'custom_plugins'),
    ],
    hiddenimports=[
        'jieba',
        'jieba.analyse',
        'rank_bm25',
        'faiss',
        'pypdf',
        'pypdf._reader',
        'pypdf._page',
        'pypdf.generic',
        'pypdf.filters',
        'pypdf._utils',
        'docx',
        'docx.shared',
        'docx.document',
        'requests',
        'src',
        'src.config_manager',
        'src.config_manager.manager',
        'src.knowledge_base',
        'src.knowledge_base.manager',
        'src.knowledge_base.bm25_retriever',
        'src.knowledge_base.vector_retriever',
        'src.knowledge_base.hybrid_retriever',
        'src.knowledge_base.document_loader',
        'src.knowledge_base.embedding_client',
        'src.agent',
        'src.agent.client',
        'src.agent.service',
        'src.agent.orchestrator_agent',
        'src.agent.skill_loader',
        'src.agent.mcp_client',
        'src.agent.subagents',
        'src.agent.subagents.base',
        'src.agent.subagents.registry',
        'src.agent.subagents.log_analyzer',
        'src.log_metadata',
        'src.log_metadata.manager',
        'src.plugin_selection',
        'src.plugin_selection.manager',
        'src.utils',
        'src.utils.file_utils',
        'src.utils.cache',
        'src.utils.logger',
        'plugins',
        'plugins.manager',
        'plugins.base',
        'plugins.renderer',
        'plugins.renderer.html_renderer',
        'dateutil',
        'chardet',
        'pandas',
        'python-dateutil'],
    hookspath=[os.path.join(project_root, 'hooks')],
    hooksconfig={},
    runtime_hooks=[os.path.join(project_root, 'hooks/runtime_hook.py')],
    # 排除不必要的模块以减小体积
    excludes=[
        'pytest',
        'unittest',
        'tkinter',
        '_tkinter',
        'IPython',
        'jupyter',
        'notebook',
        'matplotlib',
        'numpy.f2py',
        'scipy',
        'scipy.linalg',
        'scipy.sparse',
        'scipy.special',
        'scipy.stats',
        'PIL',
        'cv2',
        'pillow',
        'sphinx',
        'docutils',
        'pydoc',
        'doctest',
        'distutils',
        'distutils.command',
        'setuptools',
        'pkg_resources',
        'email.mime',
        'html.parser',
        'pytz',
        'pyarrow',
        'sympy',
        'nbconvert',
        'nbformat',
        'jupyter_client',
        'jupyter_core',
        # serve 专属排除：Web/Flask 相关
        'flask',
        'flask.json',
        'flask_login',
        'flask_sqlalchemy',
        'flask_wtf',
        'flask_compress',
        'werkzeug',
        'werkzeug.serving',
        'jinja2',
        'sqlalchemy',
        'itsdangerous',
        'src.web',
        'src.auth',
        'src.models',
        'src.storage',
        'src.session_manager',
        'src.user_config_manager',
        'src.cli',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=2,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='log_analyze_serve',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
